# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a63dcb9e1ace6621c3410043558ff697fb0830a46b95fd2d6df9182b15f26ab4fef3fee21184fbb0079a482fe26329be5ab4c2f122de430bfe7470ff39d5c12

test:
  secret_key_base: a46703928c5797e85d412d8642a965834833d4358f4634c539e117b64189460a5a56c213e9bc60c467f49cd896cef32c970e46ce301f97c2a4d0664613a771c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
